version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d/:ro

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: taskmanager
      JWT_SECRET: votre_secret_jwt_super_securise
      ORIGIN: http://localhost:8081
    depends_on:
      - db
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      args:
        REACT_APP_API_URL: http://localhost:3000/api
    ports:
      - "8081:80"
    depends_on:
      - server

volumes:
  db_data:
